FROM python:3.10-slim
WORKDIR /app/src

COPY requirements.txt .
RUN pip install --no-cache-dir streamlit==1.28.0 requests==2.31.0

COPY src/ui/ ./ui/

EXPOSE 8501
CMD ["streamlit", "run", "ui/ui.py", "--server.port=8501", "--server.address=0.0.0.0"]