FROM python:3.10-slim
WORKDIR /app/src

# Install gcc for PyTorch/Scikit-learn
RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir torch==2.0.1 fastapi==0.103.1 uvicorn==0.23.2 numpy==1.24.3 pandas==2.0.3 matplotlib==3.7.2 scikit-learn==1.3.0

COPY src/model.py .
COPY src/api.py .

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]